### ISSUE TITLE
Can't get the URL that needs to be sent

### ISSUE THREAD

**Issue by Sagi313** [M4cs/BlackEye-Python#19]
I choose an option, and I get the following:
* Starting php server...
* Starting ngrok server..
* Send this like to the victim:  

Where the URL is supposed to be, I get nothing. Installed ngrok, using python3, Kali-linux
Thanks.

**Comment by ashutoshsati** [comment]
Same problem...

**Comment by Sagi313** [comment]
seems that the problem was the port. 
I changed the port in my ngrok terminal to 8080.
than i went into ngrok's site, and the link was there

**Comment by ashutoshsati** [comment]
What was the exact command you used to change the port in the ngrok terminal?Can you pls ellaborate? Thanks.

**Comment by Sagi313** [comment]
> What was the exact command you used to change the port in the ngrok terminal?Can you pls ellaborate? Thanks.

./ngrok http 8080. This will set your ngrok server to port 8080. then, open "ngrok.com" ->endpoints->status. You should see 2 links, both do the same

**Comment by ashutoshsati** [comment]
![20210325_184215.jpg](https://user-images.githubusercontent.com/81195544/112478274-d94ac200-8d99-11eb-85c9-89b916c50f60.jpg)

**Comment by ashutoshsati** [comment]
Im getting this after i did ./ngrok http 8080. After this?

**Comment by ashutoshsati** [comment]
![20210325_184652.jpg](https://user-images.githubusercontent.com/81195544/112478908-7ad21380-8d9a-11eb-992c-3745eea8c9cb.jpg)

**Comment by Sagi313** [comment]
first set the ngrok server, then run the blackeye .
That's what fixed my issue. beside that, can't help much
